development:
  adapter: postgresql
  encoding: unicode
  database: dvdrental
  pool: 5
  username: Mixer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dvdrental
  pool: 5
  username: Mixer
  password: